home/urls.py
from django.urls import path
from . import views
from .views import signup_view


urlpatterns = [
    path("", views.home, name="home"),
    path("teams/", views.teams, name="team"),
    path("login/", views.login_view, name="login"),
    path("signup/", signup_view, name="signup"),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/delete', views.delete_profile, name='delete_profile'),
    path('upload/', views.upload_image, name='upload_image'),
    path('images/<int:pk>/edit/', views.edit_image, name='edit_image'),
    path('images/<int:pk>/delete/', views.delete_image, name='delete_image'),
]

summertrails_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('authentication.urls')),
    path("", include("home.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.contrib.auth.models import AbstractUser, Group as AuthGroup
from django.db import models
from cloudinary.models import CloudinaryField

class User(AbstractUser):
    profile_image = models.ImageField(upload_to='profile_images', blank=True, null=True)
    main_location = models.CharField(max_length=100, blank=True, null=True)
    biography = models.TextField(blank=True, null=True)
    interests = models.CharField(max_length=255, blank=True, null=True)
    groups = models.ManyToManyField(AuthGroup, related_name='home_users')
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        verbose_name='user permissions',
        blank=True,
        related_name='home_users',
        help_text='Specific permissions for this user.',
        related_query_name='home_user',
    )
    def __str__(self):
        return self.username
    
class PhotoImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = CloudinaryField('image')
    title = models.CharField(max_length=100)
    content = models.TextField()
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)

    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from authentication.models import User, PhotoImage
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email", "password1", "password2")

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = PhotoImage
        fields = ('image', 'title', 'content', 'latitude', 'longitude')

class ImageForm(forms.ModelForm):
    class Meta:
        model = PhotoImage
        fields = ['image', 'title', 'content', 'latitude', 'longitude']

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from home.forms import SignUpForm, UploadImageForm, ImageForm
from authentication.models import PhotoImage

def home(request):
    images = PhotoImage.objects.all()
    context = {'images': images}
    return render(request, "index.html", context)

def teams(request):
    '''View function for teams page of site.'''
    return render(request, "team.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            messages.error(request, "Invalid username or password.")
    return render(request, "login.html")

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account created for {username}! Please login.")
            return redirect('login')
        else:
            messages.error(request, "Invalid form data.")
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def logout_view(request):
    logout(request)
    messages.success(request, "Logged out successfully!")
    return redirect('/')

@login_required
def profile(request):
    if request.method == 'POST':
        user = request.user
        user.main_location = request.POST.get('main_location')
        user.biography = request.POST.get('biography')
        user.interests = request.POST.get('interests')
        profile_image = request.FILES.get('profile_image')
        if profile_image:
            user.profile_image = profile_image
        try:
            user.save()
            messages.success(request, 'Profile updated successfully.')
        except Exception as e:
            messages.error(request, f'An error occurred: {str(e)}')
        return redirect('profile') # Redirect to profile page
    
    return render(request, 'profile.html')

@login_required
def delete_profile(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
        return redirect('/')
    return render(request, 'delete_profile.html')

@login_required(login_url='signup')
def upload_image(request):
    if request.method == 'POST':
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            image = form.save(commit=False)
            image.user = request.user
            image.save()
            return redirect('home')
    else:
        form = UploadImageForm()
    
    return render(request, 'upload_image.html', {'form': form})

@login_required
def edit_image(request, pk):
    image = get_object_or_404(PhotoImage, pk=pk)

    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES, instance=image)
        if form.is_valid():
            image = form.save()
            return redirect('profile')
    else:
        form = ImageForm(instance=image)

    return render(request, 'edit_image.html', {'form': form, 'image': image})

@login_required
def delete_image(request, pk):
    image = get_object_or_404(PhotoImage, pk=pk)
    if request.method == 'POST':
        image.delete()
        messages.success(request, "Post deleted successfully!")
        return redirect('profile')
    return render(request, 'delete_image.html', {'image': image})

home/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <title>SummerTrails</title>
  <meta name="viewport" content="initial-scale=1,maximum-scale=1.0,user-scalable=no" />

  <!-- Main css file-->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
  <!-- Bootstrap icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
  <!-- Font Awesome -->
  <script src="https://kit.fontawesome.com/dd3b9a0c61.js" crossorigin="anonymous"></script>
  <!-- Mapbox -->
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css" rel="stylesheet" />
  <script src="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js"></script>
</head>

<body>
  <nav class="navbar fixed-top foreground-bg">
    <div class="container-fluid">
      <a class="navbar-brand navbar-title accent-text-color" href="{% url 'home' %}">SummerTrails</a>
      <button class="navbar-toggler accent-bg" type="button" data-bs-toggle="offcanvas"
        data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header foreground-bg">
          <h5 class="offcanvas-title h1 accent-text-color" id="offcanvasNavbarLabel">
            SummerTrails Menu
          </h5>
          <button type="button" class="btn-close accent-bg" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body foreground-bg">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'profile' %}">Profile</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'signup' %}">Sign Up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'team' %}">Our Team</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <!-- Mobile view navigation -->
  <nav class="navbar fixed-bottom navbar-light foreground-bg">
    <div class="container-fluid px-5 d-lg-none">
      <a href="{% url 'home' %}" class="btn btn-floating accent-bg">
        <i class="bi bi-house-door-fill main-text-color"></i>
      </a>
      <a href="{% url 'upload_image' %}" class="btn btn-floating accent-bg">
        <i class="bi bi-camera-fill main-text-color"></i>
      </a>
      {% if user.is_authenticated %}
      <a href="{% url 'profile' %}" class="btn btn-floating accent-bg">
        <i class="bi bi-person-fill main-text-color"></i>
        {{ user.username }}
      </a>
      {% else %}
      <a href="{% url 'login' %}" class="btn btn-floating main-text-color accent-bg">
        <i class="bi bi-person-fill-add main-text-color"></i>
        Login
      </a>
      {% endif %}
    </div>
  </nav>

  {% block content %}{% endblock content %}
  <!-- jQuery -->
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
  <script src="{% static 'js/index.js' %}"></script>
</body>

</html>

home/templates/delete_profile.html
{% extends 'base.html' %}
{% block content %}
<section id="delete-profile" class="container w-75 m-auto pt-5">
  <h2>Delete Profile</h2>
  <p>Are you sure you want to delete your profile?</p>
  <form action="{% url 'delete_profile' %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
</section>
{% endblock content %}

home/templates/edit_image.html
{% extends 'base.html' %}

{% block content %}
<section id="edit-image" class="container w-75 m-auto pt-5">
  <h2>Edit Image</h2>
  <form action="{% url 'edit_image' pk=image.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="image">Image</label>
      <input type="file" class="form-control-file" id="image" name="image">
    </div>
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" class="form-control" id="title" name="title" value="{{ image.title }}" required>
    </div>
    <div class="form-group">
      <label for="content">Content</label>
      <textarea class="form-control" id="content" name="content" rows="3">{{ image.content }}</textarea>
    </div>
    <div class="form-group">
      <label for="latitude">Latitude</label>
      <input type="text" class="form-control" id="latitude" name="latitude" value="{{ image.latitude }}">
    </div>
    <div class="form-group">
      <label for="longitude">Longitude</label>
      <input type="text" class="form-control" id="longitude" name="longitude" value="{{ image.longitude }}">
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
  </form>
  <form action="{% url 'delete_image' pk=image.pk %}" method="POST" class="mt-4" onsubmit="return confirm('Are you sure you want to delete this photo?');">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete Photo</button>
  </form>
</section>
{% endblock content %}

home/templates/edit_profile.html
{% extends 'base.html' %} {% block content %} {% extends 'base.html' %} {% block
content %}
<section id="edit-profile" class="container w-75 m-auto pt-5">
  <h2>Edit Profile</h2>
  <form
    action="{% url 'edit_profile' %}"
    method="POST"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username</label>
      <input
        type="text"
        class="form-control"
        id="username"
        name="username"
        value="{{ user.username }}"
        required
      />
    </div>
    <div class="form-group">
      <label for="email">Email</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        value="{{ user.email }}"
        required
      />
    </div>
    <div class="form-group">
      <label for="profile_image">Profile Image</label>
      <input
        type="file"
        class="form-control-file"
        id="profile_image"
        name="profile_image"
      />
    </div>
    <div class="form-group">
      <label for="main_location">Main Location</label>
      <input
        type="text"
        class="form-control"
        id="main_location"
        name="main_location"
        value="{{ user.main_location }}"
      />
    </div>
    <div class="form-group">
      <label for="biography">Biography</label>
      <textarea class="form-control" id="biography" name="biography" rows="3">
{{ user.biography }}</textarea
      >
    </div>
    <div class="form-group">
      <label for="interests">Interests</label>
      <input
        type="text"
        class="form-control"
        id="interests"
        name="interests"
        value="{{ user.interests }}"
      />
    </div>
    <button type="submit" class="btn btn-primary">Save Changes</button>
  </form>
</section>
{% endblock content %} {% endblock content %}

home/templates/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div id="map"></div>
{% endblock content %}

home/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section id="login" class="container w-100 m-auto h-100 pt-5 bg-light">
  <div class="w-75 mx-auto pt-4">
    <h2 class="pt-5">Login Details</h2>
    {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'success' %}
          <div class="alert alert-success mt-4">
            {{ message }}
          </div>
        {% elif message.tags == 'error' %}
          <div class="alert alert-danger mt-4">
            {{ message }}
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}
    <form action="{% url 'login' %}" method="POST" class="pt-4">
      {% csrf_token %}
      <div class="form-group">
        <label for="username">Username</label>
        <input
          type="text"
          class="form-control"
          name="username"
          id="username"
          aria-label="Enter username"
          placeholder="Enter username"
          required
        />
      </div>

      <div class="form-group mt-2">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          name="password"
          id="password"
          placeholder="Password"
          required
        />
      </div>

      <button type="submit" class="accent-button btn mt-4">Submit</button>
      <br />

      <div class="mt-4">
        <a href="{% url 'signup' %}" class="login__link"> Register </a>
      </div>

      
    </form>

  </div>
</section>
{% endblock content %}

home/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="profile pt-5 pb-5 text-left w-75 mx-auto mt-3">
  {% if messages %}
  {% for message in messages %}
    {% if message.tags == 'success' %}
      <div class="alert alert-success mt-4">
        {{ message }}
      </div>
    {% elif message.tags == 'error' %}
      <div class="alert alert-danger mt-4">
        {{ message }}
      </div>
    {% endif %}
  {% endfor %}
{% endif %}
  <div class="profile__data  mt-5">
    <h2 class="my-3">Profile</h2>
    {% if user.profile_image %}
    <p>
      <img src="{{ user.profile_image.url }}" class="w-100 rounded border" alt="Profile Picture" />
    </p>
    {% else %}
    Profile Image:
    <p>No profile image available</p>
    {% endif %}
    <p class="mb-1"><strong>Username:</strong> {{ user.username }}</p>
    <p class="mb-1"><strong>Email:</strong> {{ user.email }}</p>
    <p class="mb-1"><strong>Main Location:</strong> {{ user.main_location }}</p>
    <p class="mb-1"><strong>Biography:</strong> {{ user.biography }}</p>
    <p class="mb-1"><strong>Interests:</strong> {{ user.interests }}</p>

    <!-- 
    <a href="" class="btn btn-primary">Edit Profile</a>
    -->
    <a href="{% url 'delete_profile' %}" class="btn btn-danger mt-3 mb-3">Delete Profile</a>
  </div>

  <form action="/profile/" method="POST" enctype="multipart/form-data" class="rounded border p-3 profile__form w-90 mx-auto mt-3">
    {% csrf_token %}
    <div class="form-group">
      <label for="profile_image">Profile Image:</label>
      <input type="file" name="profile_image" id="profile_image" />
    </div>

    <div class="form-group mt-2">
      <label for="main_location">Main Location:</label>
      <input class="form-control" type="text" name="main_location" value="{{ user.main_location }}" />
    </div>

    <div class="form-group mt-2">
      <label for="biography">Biography:</label>
      <textarea class="form-control" name="biography">{{ user.biography }}</textarea>
    </div>
    <div class="form-group mt-2">
      <label for="interests" class="font-weight-bold">Interests:</label>
      <input type="text" name="interests" class="form-control" value="{{ user.interests }}" />
    </div>

    <input type="submit" class="btn btn-primary mt-3" value="Update Profile" />

  </form>


  <h3 class="pt-4 text-left">My Posts:</h3>
  {% for post in user.photoimage_set.all %}
  <div class="card text-center mb-5" style="width: 18rem;">
    <div class="card-body border">
      <img src="{{ post.image.url }}" alt="{{ post.title }}" class="card-img-top" />
        <p class="text">Title: {{ post.title }}</p>
        <p class="text">Content: {{ post.content }}</p>
      <a href="{% url 'edit_image' pk=post.id %}" class="btn btn-primary">Edit</a>
      </div>
  </div>
  {% empty %}
    <p class="mb-5 pb-5">No posts available.</p>
  {% endfor %}
  </div>



  
</div>
{% endblock %}

home/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Signup Form -->
<section id="signup" class="container w-100 m-auto py-5 bg-light">
  <div class="w-75 my-5 mx-auto">
    <h2 class="mt-5">Signup Form</h2>
    {% if messages %}
      {% for message in messages %}
        {% if message.tags == 'success' %}
          <div class="alert alert-success mt-4">
            {{ message }}
          </div>
        {% elif message.tags == 'error' %}
          <div class="alert alert-danger mt-4">
            {{ message }}
          </div>
        {% endif %}
      {% endfor %}
    {% endif %}
    <form action="{% url 'signup' %}" method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="emailAddress">Email address</label>
        <input
          type="email"
          class="form-control"
          name="email"
          id="emailAddress"
          aria-label="Enter Email"
          placeholder="Enter email"
          required
        />
      </div>
      <div class="form-group mt-2">
        <label for="username">Username</label>
        <input
          type="text"
          class="form-control"
          name="username"
          id="username"
          aria-label="Enter username"
          placeholder="Enter username"
          required
        />
      </div>
      <div class="form-group mt-2">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          name="password1"
          id="password"
          placeholder="Password"
          required
        />
      </div>
      <div class="form-group mt-2">
        <label for="confirmPassword">Confirm Password</label>
        <input
          type="password"
          class="form-control"
          name="password2"
          id="confirmPassword"
          placeholder="Password"
          required
        />
      </div>

      <button type="submit" class="btn accent-button mt-2">Submit</button>
      <div>
        <small id="emailHelp" class="form-text text-muted"
          >We'll never share your email with anyone else.</small
        >
      </div>
    </form>
  </div>
</section>

{% endblock content %}

home/templates/team.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- Profile Cards Section-->
<section id="profile-card" class="w-100 py-5 bg-light">
  <div class="profile-card__context w-75 m-auto my-4">
    <h3 class="h1">Behind SummerTrails</h3>
    <p>
      We are a small development team that got together to build a summer team
      app for a hackathon.
    </p>
  </div>
  <div class="card w-75 mb-3 m-auto border border-dark">
    <img
      src="https://camo.githubusercontent.com/4310ec844ef8d30a33b27c7aa4c62ade94056190a8f6be3500b977b481e549fd/68747470733a2f2f63612e736c61636b2d656467652e636f6d2f54304c3330423230322d55303353524448333253462d6166303231643364356635612d353132"
      class="card-img-top profile-image"
      alt="Full Stack Developer, Callum Dennis"
    />
    <div class="card-body text-center">
      <h5 class="card-title main-text-color">Callum Dennis</h5>
      <p class="card-text secondary-text-color">Full Stack Developer</p>
      <ul class="social-list">
        <li>
          <a href="#"  target="_blank"  aria-label="Visit Callum's Github page">
            <i class="fa-brands fa-github social-icons"></i>
          </a>
        </li>
        <li>
          <a href="#"  target="_blank"  aria-label="Visit Callum's linkedin page">
            <i class="fa-brands fa-linkedin social-icons"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="card w-75 mb-3 m-auto border border-dark">
    <img
      src="https://camo.githubusercontent.com/c52dce8c7458373ea7a66d606c7904e3a27b62aa4e3479a6485823ba0bec23d2/68747470733a2f2f63612e736c61636b2d656467652e636f6d2f54304c3330423230322d55303330574634354e4b562d3137323062366635396234372d353132"
      class="card-img-top"
      alt="Full Stack Developer, Christian Brown"
    />
    <div class="card-body text-center">
      <h5 class="card-title main-text-color">Christian Brown</h5>
      <p class="card-text secondary-text-color">Project Manager/Backend Developer</p>
      <ul class="social-list">
        <li>
          <a href="#"  target="_blank"  aria-label="Visit Christian's Github page">
            <i class="fa-brands fa-github social-icons"></i>
          </a>
        </li>
        <li>
          <a href="#" target="_blank"  aria-label="Visit Christian's linkedin page">
            <i class="fa-brands fa-linkedin social-icons"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="card w-75 mb-3 m-auto border border-dark">
    <img
      src="https://camo.githubusercontent.com/4ba201bf982c3b123228d03e8329551fa67229de0bbdbbfbedd0b3b2515e8bb4/68747470733a2f2f63612e736c61636b2d656467652e636f6d2f54304c3330423230322d5530334d32324b464634362d3131613164316239343363642d353132"
      class="card-img-top"
      alt="Full Stack Developer, Nicholas Tanskanen"
    />
    <div class="card-body text-center">
      <h5 class="card-title main-text-color">Niclas Tanskanen</h5>
      <p class="card-text secondary-text-color">Backend Developer</p>
      <ul class="social-list">
        <li>
          <a href="#"  target="_blank"  aria-label="Visit Niclas's Github page">
            <i class="fa-brands fa-github social-icons"></i>
          </a>
        </li>
        <li>
          <a href="#"  target="_blank"  aria-label="Visit Niclas's linkedin page">
            <i class="fa-brands fa-linkedin social-icons"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="card w-75 mb-3 m-auto border border-dark">
    <img
      src="https://camo.githubusercontent.com/14a128ab1562b3319f912a8435581c54c045965f7d2bffaaf619f1cc55229b67/68747470733a2f2f63612e736c61636b2d656467652e636f6d2f54304c3330423230322d55303153304442373148382d3631313963306535393463332d353132"
      class="card-img-top"
      alt="Full Stack Developer, Chinonso Olejeme"
    />
    <div class="card-body text-center">
      <h5 class="card-title main-text-color">Chinonso Olejeme</h5>
      <p class="card-text secondary-text-color">Front End Developer</p>
      <ul class="social-list">
        <li>
          <a href="#"  target="_blank"  aria-label="Visit Chinonso's Github page">
            <i class="fa-brands fa-github social-icons"></i>
          </a>
        </li>
        <li>
          <a href="#"  target="_blank"  aria-label="Visit Chinonso's linkedin page">
            <i class="fa-brands fa-linkedin social-icons"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="card w-75 mb-5 m-auto border border-dark">
    <img
      src="https://camo.githubusercontent.com/95ba0ccf3f54632ba9bca4a29772b86cee255b33b34f86bd07dbbc8a439f0aa7/68747470733a2f2f63612e736c61636b2d656467652e636f6d2f54304c3330423230322d55303538593633415939462d6132333462316664646238642d353132"
      class="card-img-top"
      alt="Full Stack Developer, Jhoan Trujillo"
    />
    <div class="card-body text-center">
      <h5 class="card-title main-text-color">Jhoan Trujillo</h5>
      <p class="card-text secondary-text-color">Front End Developer</p>
      <ul class="social-list">
        <li>
          <a href="#"  target="_blank"  aria-label="Visit Jhoan's Github page">
            <i class="fa-brands fa-github social-icons"></i>
          </a>
        </li>
        <li>
          <a href="https://www.linkedin.com/in/jhoan-trujillo-92b03517b/" target="_blank" aria-label="Visit Jhoan's linkedin page">
            <i class="fa-brands fa-linkedin social-icons"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</section>

{% endblock content %}

home/templates/upload_image.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section id="upload-image" class="container w-75 m-auto pt-5">
  <h2>Upload Image</h2>
  <form action="{% url 'upload_image' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="image">Image</label>
      <input type="file" class="form-control-file" name="image" id="image" accept="image/*" required>
    </div>
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" class="form-control" name="title" id="title" required>
    </div>
    <div class="form-group">
      <label for="content">Content</label>
      <textarea class="form-control" name="content" id="content" rows="5" required></textarea>
    </div>
    <div class="form-group">
      <label for="latitude">Latitude</label>
      <input type="number" class="form-control" name="latitude" id="latitude" step="0.000001">
    </div>
    <div class="form-group">
      <label for="longitude">Longitude</label>
      <input type="number" class="form-control" name="longitude" id="longitude" step="0.000001">
    </div>

    <button type="submit" class="btn btn-primary mt-2">Upload</button>
  </form>
</section>
{% endblock %}